name: Build and Deploy
on:
  push:
    branches:
      - "main"
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    if: |
      ${{ contains(github.event.head_commit.message, 'feat') }} ||
      ${{ contains(github.event.head_commit.message, 'ci') }} ||
      ${{ contains(github.event.head_commit.message, 'fix') }}
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          yarn
          yarn build
        env:
          PUBLIC_URL: https://${{ github.repository_owner }}.github.io/pose-detector/
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.